# yml file for CIs using https://github.com/xu-cheng/latex-action
name: CI-compilarotracarpeta
on: [push]
jobs:
  compilar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: holaMundoB.tex
          working_directory: carpeta
      - name: subidaHolaMundo
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: carpeta/holaMundoB.pdf


#      - name: Download a Build Artifact
#        uses: actions/download-artifact@v3
#        with: 
#          name: PDF 
#      - name: Display structure of downloaded files
#        run: ls -R
