# yml file for CIs using https://github.com/xu-cheng/latex-action
name: CI-holaMundo
on: [push]
jobs:
  compilarHolaMundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
        
